// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use DATABASE_URL in production (e.g. Vercel); fallback for build/generate when env is not set
const databaseUrl =
  typeof process.env["DATABASE_URL"] === "string" && process.env["DATABASE_URL"].trim()
    ? process.env["DATABASE_URL"]
    : "file:./resource-list.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
