// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Prefer local development secrets in .env.local, then fallback to .env.
loadEnv({ path: ".env.local" });
loadEnv();

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl || !databaseUrl.trim()) {
  throw new Error("DATABASE_URL is required for Prisma configuration.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
